baseURL: "https://Zpn11.github.io"
languageCode: "en-us"
title: "April"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 5
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID
publishDir: "docs"
cleanDestinationDir: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: about
      name: About
      title: About
      url: /#about
      weight: 1
    - identifier: cv
      name: Personal CV
      title: Personal CV
      url: /#experience
      weight: 2
    - identifier: works
      name: Personal Works
      title: Personal Works
      url: /#projects
      weight: 3
    - identifier: clife
      name: Life
      title: Life
      url: /#achievements
      weight: 4
    - identifier: contact
      name: Contact
      title: Contact
      url: /#contact
      weight: 5
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "April"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "April" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hello, my name is"
    title: "April"
    subtitle: "an outgoing girl"
    content: "This is my personal website, you can learn about me by this website."
    image: /images/profile.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Contact"
      url: "#contact"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-weibo
          url: https://weibo.com/u/5816536656
        - icon: fab fa-tiktok
          url: https://v.douyin.com/iATExwDT/
      customIcons:
        - icon: /images/xiaohongshu.min.svg
          url: "https://www.xiaohongshu.com/user/profile/6127ac13000000002002fde0"

  # About
  about:
    enable: true
    title: "About Me"
    image: ""
    content: |-
      I am a student. My English name is April, and my Chinese name is Puning Zhang. I like life and enjoy life. I like to travel and I want to travel around the world. I studied piano, art, equestrian, sing  and so on. I enjoy the learning process. 
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Volunteer during a pandemic"
        company: "volunteer"
        date: "Jan 2020"
        featuredLink:
          enable: false
        content: "Volunteer to help with nucleic acid testing during pandemic."

      - job: "take part in competition"
        company: "competition"
        date: "2018"
        featuredLink:
          enable: false
        content: "Won the first prize in the National Children's Art Competition."

      - job: "take part in Summer institute."
        company: "Summer institute"
        date: "July 2024"
        info:
          enable: false
        featuredLink:
          enable: false
        content: "Attend Oriel College university Oxford and achieved great grades."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Business Administration"
        school:
          name: "Macao University of Science and technology"
          url: "https://www.must.edu.mo/index.html"
        date: "2023 - 2027"
        content: |-
          Take professional courses in business administration, marketing, macroeconomics, financial accounting, and more. Participated in school club activities and served as the cadre of the debate club.
      - title: "Senior High School"
        school:
          name: "Hengshui No.2 High School"
          url: "http://www.hsez.net/"
        date: "2020 - 2023"
        content: |-
          I studied hard in high school for three years and participated in many volunteer activities. 
      - title: "Junior High School"
        school:
          name: "Yuhua Junior High School"
        date: "2017 - 2020"
        content: |-
          I spent three years in this school, met some very good teachers and laid foundation for future study.

  # Achievements
  achievements:
    enable: true
    title: "Life"
    items:
      - title: 
        image: /images/1.jpg
      - title: 
        image: /images/2.jpg
      - title:
        image: /images/4.jpg
      - title:
        image: /images/5.jpg
      - title:
        image: /images/6.jpg
      - title:
        image: /images/7.jpg

  # projects
  projects:
    enable: true
    title: "Personal Works"
    items:
      - title: 'Case Analysis: Gibbons v. Ogden (1824)'
        image: /images/projects/transcript.jpg
        featured:
          name: Detail
          link: /projects/analyse

      - title: Enterprise interview 
        # content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/transcript.jpg
        featured:
          name: Detail
          link: /projects/interview
        # badges:
        #   - "Interview"

      - title: Journey Under the Midnight Sun’s Tragic Writing
        # content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/writing.jpg
        featured:
          name: Detail
          link: /pdf/writing.pdf

      - title: Marketing analysis of DJI
        # content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/dji.jpg
        featured:
          name: Detail
          link: /pdf/DJI.pdf

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:ppuningz9@163.com
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Email address"
      messageCaption: "Your message"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      instagram: https://www.instagram.com/zpn111/profilecard/
      tiktok: https://v.douyin.com/iATExwDT/
      xiaoHongShu: https://www.xiaohongshu.com/user/profile/6127ac13000000002002fde0

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
